### ISSUE TITLE
Installation: DLL load failed

### ISSUE THREAD

**Issue by nvladimus** [WyssCenter/pAPRica#13]
Dear authors,
Very cool paper, congratulations! I have some beginner issues which I hope to resolve with your help. I installed `paprica` according to docs, but unfortunately it does not load:
```
>>> import paprica
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Nikita\anaconda3\envs\paprica\lib\site-packages\paprica\__init__.py", line 19, in <module>
    from . import loader, parser, stitcher, viewer, segmenter, atlaser, converter, runner, batcher
  File "C:\Users\Nikita\anaconda3\envs\paprica\lib\site-packages\paprica\loader.py", line 18, in <module>
    import pyapr
  File "C:\Users\Nikita\anaconda3\envs\paprica\lib\site-packages\pyapr\__init__.py", line 43, in <module>
    from .data_containers import *
  File "C:\Users\Nikita\anaconda3\envs\paprica\lib\site-packages\pyapr\data_containers\__init__.py", line 1, in <module>
    from _pyaprwrapper.data_containers import APR, APRParameters, FloatParticles, ShortParticles, LongParticles, \
ImportError: DLL load failed: The specified module could not be found.
```
Is the published code complete? Any tips are highly appreciated!

**Comment by joeljonsson** [comment]
Thank you!

Windows is always a bit problematic... I am not able to replicate this issue though. Can you tell me which system and python versions you are using?

It seems like the issue is with [pyapr](https://github.com/AdaptiveParticles/pyapr). Could you try installing pyapr only (`pip install pyapr` ) in a new environment and then try to import it, to see if the problem persists? 

If it does, it would be helpful to know which dll is missing. You can (hopefully) find this out by using a dependency walker, e.g. https://github.com/lucasg/Dependencies, on the `_pyaprwrapper` file (this should be located in the site-packages directory and named something like `_pyaprwrapper.cp39-win_amd64`).

Alternatively, you could try installing pyapr from source (see https://github.com/AdaptiveParticles/pyapr/blob/master/INSTALL.md and https://github.com/AdaptiveParticles/LibAPR#building-on-windows). Note that the instructions are somewhat dated -- they should still work, but there might be easier ways to do it now.

**Comment by nvladimus** [comment]
Hi,
Thanks for the tips! I am using Win10 x64, Anaconda 3, new clean environment with python 3.7.16. The `pip install pyapr` installs without any issues, but the import fails. I will try the dependency walker and installation from source tomorrow.

**Comment by nvladimus** [comment]
Hi, I ran the Dependences, it looks like I am missing a libomp140 DLL:
![image](https://user-images.githubusercontent.com/10835134/216634005-7c0b95d2-cd3e-4ebb-baeb-7533062f5b08.png)
Google suggests this is some OpenMP library. Any tips how to fix this?

**Comment by joeljonsson** [comment]
Ah, yes. See e.g. [here](https://devblogs.microsoft.com/cppblog/improved-openmp-support-for-cpp-in-visual-studio/) for some info on OpenMP support in windows. 

The issue should be fixable by installing the llvm clang compiler. You can do this by following the first steps in [the LibAPR install instructions](https://github.com/AdaptiveParticles/LibAPR#building-on-windows) (the `choco install` steps). It might also be possible to directly install the missing runtime library.

**Comment by nvladimus** [comment]
Thanks! I installed VS with C++ support and the DLL problem seems to be solved:
```
>>> import paprica
Validation errors in config file(s).
The following fields have been reset to the default value:

plugins -> call_order
  none is not an allowed value (type=type_error.none.not_allowed)
```
I hope this error is not critical, will test next week.

**Comment by joeljonsson** [comment]
Did you manage to solve the second issue?

**Comment by nvladimus** [comment]
No, but it is not critical, I managed to run the example code.
